"""Init

Revision ID: 86361a8e0a7a
Revises: 
Create Date: 2024-07-19 13:20:00.298297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86361a8e0a7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_keys',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mapping_keys_id_'), 'mapping_keys', ['id_'], unique=True)
    op.create_table('mapping_values',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['mapping_keys.id_'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mapping_values_id_'), 'mapping_values', ['id_'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_values_id_'), table_name='mapping_values')
    op.drop_table('mapping_values')
    op.drop_index(op.f('ix_mapping_keys_id_'), table_name='mapping_keys')
    op.drop_table('mapping_keys')
    # ### end Alembic commands ###
